# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3240c03b328aedc087d931d25c5a4355100262d7b25164e66d4c62577e3d25eb0fc25123e9fa713568f2e7454a144cc4bf0433118f7835e500dccb2a0727cecb

test:
  secret_key_base: 60283df96d50e5c3fc01e7d01c3b10ffaaf27a77b76a633a040e7374dd8398b387917d1a7aa45b5590059b4bf75bd89f4ded929801da7ee4b311f15100082e75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
