# config/site.yml
defaults: &defaults
  title: Polytene
  domain: some_fancy_domain_name
  version: '0.0.1'

production:
  <<: *defaults
  base_email: polytene@some_fancy_domain_name
 
development:
  <<: *defaults
  base_email: polytene@some_fancy_domain_name
 
test:
  <<: *defaults
  base_email: polytene@some_fancy_domain_name
